package com.codename1.twitterui.controllers;


import com.codename1.rad.controllers.*;
import com.codename1.rad.models.Entity;
import com.codename1.rad.models.EntityList;
import com.codename1.rad.ui.Actions;
import com.codename1.twitterui.events.AppNavigationEvent;
import com.codename1.twitterui.providers.DemoTweetProvider;
import com.codename1.twitterui.providers.INewsProvider;
import com.codename1.twitterui.providers.ITweetProvider;
import com.codename1.twitterui.schemas.TWTApplicationSchema;
import com.codename1.twitterui.schemas.INewsCategories;
import com.codename1.twitterui.schemas.TweetSchema;
import com.codename1.twitterui.schemas.TWTUserProfileSchema;
import com.codename1.twitterui.spi.INewsFormController;
import com.codename1.twitterui.spi.ISidebarController;
import com.codename1.twitterui.spi.ITweetListController;
import com.codename1.twitterui.models.*;
import com.codename1.rad.nodes.ActionNode;
import com.codename1.rad.nodes.ViewNode;
import com.codename1.rad.schemas.Thing;

import com.codename1.twitterui.providers.DemoNewsProvider;
import com.codename1.twitterui.views.TWTGlobalTabs;
import com.codename1.twitterui.views.TWTSideBarView;
import com.codename1.twitterui.views.TWTTitleComponent;
import com.codename1.ui.FontImage;

import static com.codename1.rad.ui.UI.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class TWTApplicationController extends ApplicationController implements
        ITweetListController, ISidebarController, INewsFormController {



    private boolean demoMode = true;

    private TWTApplicationModel applicationModel;



    protected void initApplicationModel(TWTApplicationModel model) {
        model.setCurrentSection(HomeFormController.section);
        initSections(model);
    }

    protected void initSections(TWTApplicationModel model) {
        TWTApplicationSchema.Sections sections = new TWTApplicationSchema.Sections(
                HomeFormController.section,
                NewsFormController.section
        );
        model.setSections(sections);
    }



    
    static final ActionNode notInterested = action(
            label("Not interested in this"),
            icon(FontImage.MATERIAL_MOOD_BAD)
        ),
            
        unfollow = action(
            icon(FontImage.MATERIAL_REMOVE),
            label(tweet->{
                if (tweet.isEntity(TweetSchema.author)) {
                    return "Unfollow "+tweet.getEntity(TweetSchema.author).getText(Thing.identifier);
                } else if (!tweet.isEmpty(TweetSchema.authorId)){
                    return "Unfollow "+tweet.getText(TweetSchema.authorId);
                }
                return "Unfollow this user";
            })
        ),
            
        mute = action(
            icon(FontImage.MATERIAL_VOLUME_OFF),
            label(tweet->{
                if (tweet.isEntity(TweetSchema.author)) {
                    return "Mute "+tweet.getEntity(TweetSchema.author).getText(Thing.identifier);
                } else if (!tweet.isEmpty(TweetSchema.authorId)){
                    return "Mute "+tweet.getText(TweetSchema.authorId);
                }
                return "Mute this user";
            })
        ),
            
        reply = action(
            icon(FontImage.MATERIAL_CHAT_BUBBLE_OUTLINE)
        ),
        retweet = action(
            icon(FontImage.MATERIAL_FORWARD)
        ),
        favorite = action(
            icon(FontImage.MATERIAL_FAVORITE_OUTLINE)
        ),
        share = action(
            icon(FontImage.MATERIAL_SHARE)
        ),
            
        tweetDetails = action(
                   
        ),
        profile = action(
                label("Profile"),
                icon(FontImage.MATERIAL_ACCOUNT_CIRCLE)
        ),
        lists = action(label("Lists"), icon(FontImage.MATERIAL_LIST)),
        topics = action(label("Topics"), icon(FontImage.MATERIAL_CATEGORY)),
        bookmarks = action(label("Bookmarks"), icon(FontImage.MATERIAL_BOOKMARKS)),
        moments = action(label("Moments"), icon(FontImage.MATERIAL_BOLT)),
        newAccount = action(label("Create new account")),
        addExistingAccount = action(label("Add Existing Account")),
        settingsAndPrivacy = action(label("Settings and privacy")),
        helpCenter = action(label("Help Center")),
        darkMode = action(icon(FontImage.MATERIAL_LIGHTBULB_OUTLINE)),
        qrCode = action(icon(FontImage.MATERIAL_SCANNER)),
        switchProfile = action(icon(FontImage.MATERIAL_ACCOUNT_CIRCLE)),
        switchProfile2 = action(icon(FontImage.MATERIAL_ACCOUNT_BALANCE_WALLET)),
        followers = action(
                icon("Followers"),
                label("344")
        ),
        following = action(
            icon("Following"),
            label("311")
        )
        ;
    
    
    public TWTApplicationController() {

    }

    public TWTApplicationController(boolean demoMode) {
        this.demoMode = demoMode;
    }



    @Override
    public void init(Object context) {
        super.init(context);
        getApplicationModel();
        initApplicationModel(applicationModel);
        addLookup(TWTApplicationModel.class, applicationModel);
        TWTGlobalTabs menuBar = new TWTGlobalTabs(applicationModel.getEntity(), (ViewNode)getViewNode());
        addLookup(menuBar);

        addActionListener(getSettingsAction(), evt-> {
            evt.consume();
            com.codename1.ui.Component c = evt.getContext().getEventSource();
            ViewController vc = ViewController.getViewController(c);
            Controller parent = this;
            if (vc != null && vc.getFormController() != null) {
                parent = vc.getFormController();
            }
            createSettingsFormController(parent).getView().show();
        });

        applicationModel.getSections().addActionListenersTo(this);

    }
    
    
    
    private static TWTUserProfileSchema createDemoProfile() {
        TWTUserProfile p = new TWTUserProfile();
        p.set(Thing.name, "Steve Hannah");
        p.set(Thing.identifier, "@shannah78");
        p.set(Thing.thumbnailUrl, "https://www.codenameone.com/img/steve.jpg");
        return p;
    }

    @Override
    public void actionPerformed(ControllerEvent evt) {
        if (evt instanceof StartEvent) {
            evt.consume();
            new HomeFormController(this).getView().show();
            return;
        }
        evt.as(AppNavigationEvent.class, ane->{
            // When the app navigates to a new section, it should fire this event, which we use
            // to update the global navigation state - which will update the globals tabs
            // state.
            evt.consume();
            applicationModel.setCurrentSection(ane.getSection());
        });


        super.actionPerformed(evt);
    }
    
    
    
    public ViewNode createViewNode() {
        ViewNode viewNode = new ViewNode( 
            actions(TWTSideBarView.SIDEBAR_ACTIONS, createSidebarActions()),
            actions(TWTSideBarView.SIDEBAR_TOP_OVERFLOW_MENU, createSidebarTopOverflowMenuActions()),
            actions(TWTSideBarView.SIDEBAR_SETTINGS_ACTIONS, createSidebarSettingsActions()),
            actions(TWTSideBarView.SIDEBAR_BOTTOM_LEFT_ACTIONS, createSidebarBottomLeftActions()),
            actions(TWTSideBarView.SIDEBAR_BOTTOM_RIGHT_ACTIONS, createSidebarBottomRightActions()),
            actions(TWTSideBarView.SIDEBAR_TOP_ACTIONS, createSidebarTopActions()),
            actions(TWTSideBarView.SIDEBAR_STATS, createSidebarStatsActions()),
            actions(TWTGlobalTabs.GLOBAL_TABS, applicationModel.getSections().getActions()),
            actions(TWTTitleComponent.TITLE_ACTIONS, createTitleActions())
                
        );
        return viewNode;
    }


    /**
     * Override to specify actions to display in the sidebar.
     *
     * @return The actions to display in the sidebar.
     */
    public Actions createSidebarActions() {
        if (!isDemoMode()) return new Actions();
        return new Actions(profile, lists, topics, bookmarks, moments);
    }

    public Actions createSidebarTopOverflowMenuActions() {
        if (!isDemoMode()) return new Actions();
        return new Actions(newAccount, addExistingAccount);
    }

    public Actions createSidebarBottomLeftActions() {
        if (!isDemoMode()) return new Actions();
        return new Actions(darkMode);
    }

    public Actions createSidebarSettingsActions() {
        if (!isDemoMode()) return new Actions();
        return new Actions(settingsAndPrivacy, helpCenter);
    }

    public Actions createSidebarBottomRightActions() {
        if (!isDemoMode()) return new Actions();
        return new Actions(qrCode);
    }

    public Actions createSidebarTopActions() {
        if (!isDemoMode()) return new Actions();
        return new Actions(switchProfile, switchProfile2);
    }

    public Actions createSidebarStatsActions() {
        if (!isDemoMode()) return new Actions();
        return new Actions(following, followers);
    }





    public Actions createTitleActions() {
        return new Actions(getSettingsAction());
    }


    public boolean isDemoMode() {
        return demoMode;
    }


    public TWTApplicationModel getApplicationModel() {
        if (applicationModel == null) {
            applicationModel = createApplicationModel();

        }
        return applicationModel;
    }

    public TWTApplicationModel createApplicationModel() {
        return new TWTApplicationModelImpl();
    }

    protected TWTUserProfileSchema createUserProfile() {
        if (isDemoMode()) {
            return createDemoProfile();
        }
        return new TWTUserProfile();
    }

    public Actions createTweetMenuActions() {
        return new Actions();
    }

    public Actions createTweetActions() {
        return new Actions();
    }

    public Actions createTweetProfileAvatarClickedMenuActions() {
        return new Actions();
    }

    public ActionNode createTweetClickedAction() {
        return action();
    }

    @Override
    public ITweetProvider createTweetProvider() {
        if (isDemoMode()) {
            return new DemoTweetProvider();
        }
        return null;
    }

    public SettingsFormController createSettingsFormController(Controller parent) {
        return new SettingsFormController(parent);
    }


    private ActionNode settingsAction;

    private ActionNode getSettingsAction() {
        if (settingsAction == null) {
            settingsAction = createSettingsAction();
        }
        return settingsAction;
    }

    public ActionNode createSettingsAction() {

        return action(
                icon(FontImage.MATERIAL_SETTINGS)
        );
    }

    public <T extends Entity & TweetSchema> FormController createTweetDetailsController(Controller parent, T tweet) {
        return new TweetDetailsController<T>(parent, tweet);
    }

    public FormController createHomeFormController(Controller parent) {
        return new HomeFormController(parent);
    }


    @Override
    public TWTNewsCategories getNewsCategories() {
        // This can be overridden to override the news categories.
        // It can also be overridden in the {@link NewsFormController}.
        return null;
    }

    @Override
    public INewsProvider getNewsProvider() {
        // Can be overridden to get the news provider.
        // It an also be overridden in {@link NewsFormController}.
        return null;
    }
}